# Generated by Django 5.2.7 on 2025-11-11 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(auto_now_add=True, null=True, verbose_name="дата оплаты")),
                ("amount", models.FloatField(blank=True, null=True, verbose_name="сумма оплаты")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("наличные", "наличные"), ("перевод на счет", "перевод на счет")],
                        default="наличные",
                        max_length=15,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "paid_course",
                    models.ManyToManyField(
                        blank=True, related_name="payments", to="studies.course", verbose_name="оплаченный курс"
                    ),
                ),
                (
                    "paid_lesson",
                    models.ManyToManyField(
                        blank=True, related_name="payments", to="studies.lesson", verbose_name="оплаченный урок"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
                "db_table": "payments",
                "ordering": ["user", "payment_date"],
            },
        ),
    ]
