# Generated by Django 5.2.7 on 2025-11-14 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0004_course_is_available_course_price_lesson_is_available_and_more"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-payment_date"], "verbose_name": "платеж", "verbose_name_plural": "платежи"},
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="дата оплаты"),
        ),
        migrations.AddField(
            model_name="payment",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="публичный ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ожидает оплаты", "Ожидает оплаты"),
                    ("Оплачено", "Оплачено"),
                    ("Ошибка оплаты", "Ошибка оплаты"),
                    ("Возвращено", "Возвращено"),
                ],
                default="Ожидает оплаты",
                max_length=15,
                verbose_name="статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name="сумма оплаты"
            ),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_lesson",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="дата создания платежа"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("наличные", "наличные"),
                    ("перевод на счет", "перевод на счет"),
                    ("Stripe онлайн-оплата", "Stripe онлайн-оплата"),
                ],
                default="Stripe онлайн-оплата",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["public_id"], name="payments_public__19f0ec_idx"),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="studies.course",
                verbose_name="оплаченный курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="studies.lesson",
                verbose_name="оплаченный урок",
            ),
        ),
    ]
