# Generated by Django 5.2.7 on 2025-11-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="название курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="images/placeholder.png",
                        null=True,
                        upload_to="images/",
                        verbose_name="превью курса",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание курса")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "db_table": "courses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="название урока")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="порядковый номер")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="images/placeholder.png",
                        null=True,
                        upload_to="images/",
                        verbose_name="превью урока",
                    ),
                ),
                ("video_url", models.URLField(blank=True, max_length=500, null=True, verbose_name="ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="studies.course",
                        verbose_name="курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "db_table": "lessons",
                "ordering": ["course", "order"],
            },
        ),
    ]
