# Generated by Django 5.2.7 on 2025-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="доступность"),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=10, verbose_name="стоимость курса"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="доступность"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10, verbose_name="стоимость урока"),
        ),
    ]
